# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\viett\OneDrive\Documents\GitHub\BdfCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\viett\OneDrive\Documents\GitHub\BdfCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\viett\OneDrive\Documents\GitHub\BdfCpp\CMakeFiles C:\Users\viett\OneDrive\Documents\GitHub\BdfCpp\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\viett\OneDrive\Documents\GitHub\BdfCpp\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named timestamp

# Build rule for target.
timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 timestamp
.PHONY : timestamp

# fast build rule for target.
timestamp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\timestamp.dir\build.make CMakeFiles/timestamp.dir/build
.PHONY : timestamp/fast

#=============================================================================
# Target rules for targets named fibonacci

# Build rule for target.
fibonacci: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 fibonacci
.PHONY : fibonacci

# fast build rule for target.
fibonacci/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fibonacci.dir\build.make CMakeFiles/fibonacci.dir/build
.PHONY : fibonacci/fast

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\helloworld.dir\build.make CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tests.dir\build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named bdfconvert

# Build rule for target.
bdfconvert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bdfconvert
.PHONY : bdfconvert

# fast build rule for target.
bdfconvert/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdfconvert.dir\build.make CMakeFiles/bdfconvert.dir/build
.PHONY : bdfconvert/fast

#=============================================================================
# Target rules for targets named copy_include

# Build rule for target.
copy_include: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 copy_include
.PHONY : copy_include

# fast build rule for target.
copy_include/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\copy_include.dir\build.make CMakeFiles/copy_include.dir/build
.PHONY : copy_include/fast

#=============================================================================
# Target rules for targets named bdf

# Build rule for target.
bdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bdf
.PHONY : bdf

# fast build rule for target.
bdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/build
.PHONY : bdf/fast

examples/fibonacci.obj: examples/fibonacci.cpp.obj
.PHONY : examples/fibonacci.obj

# target to build an object file
examples/fibonacci.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fibonacci.dir\build.make CMakeFiles/fibonacci.dir/examples/fibonacci.cpp.obj
.PHONY : examples/fibonacci.cpp.obj

examples/fibonacci.i: examples/fibonacci.cpp.i
.PHONY : examples/fibonacci.i

# target to preprocess a source file
examples/fibonacci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fibonacci.dir\build.make CMakeFiles/fibonacci.dir/examples/fibonacci.cpp.i
.PHONY : examples/fibonacci.cpp.i

examples/fibonacci.s: examples/fibonacci.cpp.s
.PHONY : examples/fibonacci.s

# target to generate assembly for a file
examples/fibonacci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fibonacci.dir\build.make CMakeFiles/fibonacci.dir/examples/fibonacci.cpp.s
.PHONY : examples/fibonacci.cpp.s

examples/helloworld.obj: examples/helloworld.cpp.obj
.PHONY : examples/helloworld.obj

# target to build an object file
examples/helloworld.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\helloworld.dir\build.make CMakeFiles/helloworld.dir/examples/helloworld.cpp.obj
.PHONY : examples/helloworld.cpp.obj

examples/helloworld.i: examples/helloworld.cpp.i
.PHONY : examples/helloworld.i

# target to preprocess a source file
examples/helloworld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\helloworld.dir\build.make CMakeFiles/helloworld.dir/examples/helloworld.cpp.i
.PHONY : examples/helloworld.cpp.i

examples/helloworld.s: examples/helloworld.cpp.s
.PHONY : examples/helloworld.s

# target to generate assembly for a file
examples/helloworld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\helloworld.dir\build.make CMakeFiles/helloworld.dir/examples/helloworld.cpp.s
.PHONY : examples/helloworld.cpp.s

examples/tests.obj: examples/tests.cpp.obj
.PHONY : examples/tests.obj

# target to build an object file
examples/tests.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tests.dir\build.make CMakeFiles/tests.dir/examples/tests.cpp.obj
.PHONY : examples/tests.cpp.obj

examples/tests.i: examples/tests.cpp.i
.PHONY : examples/tests.i

# target to preprocess a source file
examples/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tests.dir\build.make CMakeFiles/tests.dir/examples/tests.cpp.i
.PHONY : examples/tests.cpp.i

examples/tests.s: examples/tests.cpp.s
.PHONY : examples/tests.s

# target to generate assembly for a file
examples/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tests.dir\build.make CMakeFiles/tests.dir/examples/tests.cpp.s
.PHONY : examples/tests.cpp.s

src/BdfError.obj: src/BdfError.cpp.obj
.PHONY : src/BdfError.obj

# target to build an object file
src/BdfError.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfError.cpp.obj
.PHONY : src/BdfError.cpp.obj

src/BdfError.i: src/BdfError.cpp.i
.PHONY : src/BdfError.i

# target to preprocess a source file
src/BdfError.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfError.cpp.i
.PHONY : src/BdfError.cpp.i

src/BdfError.s: src/BdfError.cpp.s
.PHONY : src/BdfError.s

# target to generate assembly for a file
src/BdfError.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfError.cpp.s
.PHONY : src/BdfError.cpp.s

src/BdfHelpers.obj: src/BdfHelpers.cpp.obj
.PHONY : src/BdfHelpers.obj

# target to build an object file
src/BdfHelpers.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfHelpers.cpp.obj
.PHONY : src/BdfHelpers.cpp.obj

src/BdfHelpers.i: src/BdfHelpers.cpp.i
.PHONY : src/BdfHelpers.i

# target to preprocess a source file
src/BdfHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfHelpers.cpp.i
.PHONY : src/BdfHelpers.cpp.i

src/BdfHelpers.s: src/BdfHelpers.cpp.s
.PHONY : src/BdfHelpers.s

# target to generate assembly for a file
src/BdfHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfHelpers.cpp.s
.PHONY : src/BdfHelpers.cpp.s

src/BdfIndent.obj: src/BdfIndent.cpp.obj
.PHONY : src/BdfIndent.obj

# target to build an object file
src/BdfIndent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfIndent.cpp.obj
.PHONY : src/BdfIndent.cpp.obj

src/BdfIndent.i: src/BdfIndent.cpp.i
.PHONY : src/BdfIndent.i

# target to preprocess a source file
src/BdfIndent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfIndent.cpp.i
.PHONY : src/BdfIndent.cpp.i

src/BdfIndent.s: src/BdfIndent.cpp.s
.PHONY : src/BdfIndent.s

# target to generate assembly for a file
src/BdfIndent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfIndent.cpp.s
.PHONY : src/BdfIndent.cpp.s

src/BdfList.obj: src/BdfList.cpp.obj
.PHONY : src/BdfList.obj

# target to build an object file
src/BdfList.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfList.cpp.obj
.PHONY : src/BdfList.cpp.obj

src/BdfList.i: src/BdfList.cpp.i
.PHONY : src/BdfList.i

# target to preprocess a source file
src/BdfList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfList.cpp.i
.PHONY : src/BdfList.cpp.i

src/BdfList.s: src/BdfList.cpp.s
.PHONY : src/BdfList.s

# target to generate assembly for a file
src/BdfList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfList.cpp.s
.PHONY : src/BdfList.cpp.s

src/BdfLookupTable.obj: src/BdfLookupTable.cpp.obj
.PHONY : src/BdfLookupTable.obj

# target to build an object file
src/BdfLookupTable.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfLookupTable.cpp.obj
.PHONY : src/BdfLookupTable.cpp.obj

src/BdfLookupTable.i: src/BdfLookupTable.cpp.i
.PHONY : src/BdfLookupTable.i

# target to preprocess a source file
src/BdfLookupTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfLookupTable.cpp.i
.PHONY : src/BdfLookupTable.cpp.i

src/BdfLookupTable.s: src/BdfLookupTable.cpp.s
.PHONY : src/BdfLookupTable.s

# target to generate assembly for a file
src/BdfLookupTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfLookupTable.cpp.s
.PHONY : src/BdfLookupTable.cpp.s

src/BdfNamedList.obj: src/BdfNamedList.cpp.obj
.PHONY : src/BdfNamedList.obj

# target to build an object file
src/BdfNamedList.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfNamedList.cpp.obj
.PHONY : src/BdfNamedList.cpp.obj

src/BdfNamedList.i: src/BdfNamedList.cpp.i
.PHONY : src/BdfNamedList.i

# target to preprocess a source file
src/BdfNamedList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfNamedList.cpp.i
.PHONY : src/BdfNamedList.cpp.i

src/BdfNamedList.s: src/BdfNamedList.cpp.s
.PHONY : src/BdfNamedList.s

# target to generate assembly for a file
src/BdfNamedList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfNamedList.cpp.s
.PHONY : src/BdfNamedList.cpp.s

src/BdfObject.obj: src/BdfObject.cpp.obj
.PHONY : src/BdfObject.obj

# target to build an object file
src/BdfObject.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfObject.cpp.obj
.PHONY : src/BdfObject.cpp.obj

src/BdfObject.i: src/BdfObject.cpp.i
.PHONY : src/BdfObject.i

# target to preprocess a source file
src/BdfObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfObject.cpp.i
.PHONY : src/BdfObject.cpp.i

src/BdfObject.s: src/BdfObject.cpp.s
.PHONY : src/BdfObject.s

# target to generate assembly for a file
src/BdfObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfObject.cpp.s
.PHONY : src/BdfObject.cpp.s

src/BdfReader.obj: src/BdfReader.cpp.obj
.PHONY : src/BdfReader.obj

# target to build an object file
src/BdfReader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfReader.cpp.obj
.PHONY : src/BdfReader.cpp.obj

src/BdfReader.i: src/BdfReader.cpp.i
.PHONY : src/BdfReader.i

# target to preprocess a source file
src/BdfReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfReader.cpp.i
.PHONY : src/BdfReader.cpp.i

src/BdfReader.s: src/BdfReader.cpp.s
.PHONY : src/BdfReader.s

# target to generate assembly for a file
src/BdfReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfReader.cpp.s
.PHONY : src/BdfReader.cpp.s

src/BdfReaderHuman.obj: src/BdfReaderHuman.cpp.obj
.PHONY : src/BdfReaderHuman.obj

# target to build an object file
src/BdfReaderHuman.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfReaderHuman.cpp.obj
.PHONY : src/BdfReaderHuman.cpp.obj

src/BdfReaderHuman.i: src/BdfReaderHuman.cpp.i
.PHONY : src/BdfReaderHuman.i

# target to preprocess a source file
src/BdfReaderHuman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfReaderHuman.cpp.i
.PHONY : src/BdfReaderHuman.cpp.i

src/BdfReaderHuman.s: src/BdfReaderHuman.cpp.s
.PHONY : src/BdfReaderHuman.s

# target to generate assembly for a file
src/BdfReaderHuman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfReaderHuman.cpp.s
.PHONY : src/BdfReaderHuman.cpp.s

src/BdfStringReader.obj: src/BdfStringReader.cpp.obj
.PHONY : src/BdfStringReader.obj

# target to build an object file
src/BdfStringReader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfStringReader.cpp.obj
.PHONY : src/BdfStringReader.cpp.obj

src/BdfStringReader.i: src/BdfStringReader.cpp.i
.PHONY : src/BdfStringReader.i

# target to preprocess a source file
src/BdfStringReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfStringReader.cpp.i
.PHONY : src/BdfStringReader.cpp.i

src/BdfStringReader.s: src/BdfStringReader.cpp.s
.PHONY : src/BdfStringReader.s

# target to generate assembly for a file
src/BdfStringReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/BdfStringReader.cpp.s
.PHONY : src/BdfStringReader.cpp.s

src/version.obj: src/version.cpp.obj
.PHONY : src/version.obj

# target to build an object file
src/version.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/version.cpp.obj
.PHONY : src/version.cpp.obj

src/version.i: src/version.cpp.i
.PHONY : src/version.i

# target to preprocess a source file
src/version.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/version.cpp.i
.PHONY : src/version.cpp.i

src/version.s: src/version.cpp.s
.PHONY : src/version.s

# target to generate assembly for a file
src/version.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdf.dir\build.make CMakeFiles/bdf.dir/src/version.cpp.s
.PHONY : src/version.cpp.s

tools/bdfconvert.obj: tools/bdfconvert.cpp.obj
.PHONY : tools/bdfconvert.obj

# target to build an object file
tools/bdfconvert.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdfconvert.dir\build.make CMakeFiles/bdfconvert.dir/tools/bdfconvert.cpp.obj
.PHONY : tools/bdfconvert.cpp.obj

tools/bdfconvert.i: tools/bdfconvert.cpp.i
.PHONY : tools/bdfconvert.i

# target to preprocess a source file
tools/bdfconvert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdfconvert.dir\build.make CMakeFiles/bdfconvert.dir/tools/bdfconvert.cpp.i
.PHONY : tools/bdfconvert.cpp.i

tools/bdfconvert.s: tools/bdfconvert.cpp.s
.PHONY : tools/bdfconvert.s

# target to generate assembly for a file
tools/bdfconvert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\bdfconvert.dir\build.make CMakeFiles/bdfconvert.dir/tools/bdfconvert.cpp.s
.PHONY : tools/bdfconvert.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... copy_include
	@echo ... timestamp
	@echo ... bdf
	@echo ... bdfconvert
	@echo ... fibonacci
	@echo ... helloworld
	@echo ... tests
	@echo ... examples/fibonacci.obj
	@echo ... examples/fibonacci.i
	@echo ... examples/fibonacci.s
	@echo ... examples/helloworld.obj
	@echo ... examples/helloworld.i
	@echo ... examples/helloworld.s
	@echo ... examples/tests.obj
	@echo ... examples/tests.i
	@echo ... examples/tests.s
	@echo ... src/BdfError.obj
	@echo ... src/BdfError.i
	@echo ... src/BdfError.s
	@echo ... src/BdfHelpers.obj
	@echo ... src/BdfHelpers.i
	@echo ... src/BdfHelpers.s
	@echo ... src/BdfIndent.obj
	@echo ... src/BdfIndent.i
	@echo ... src/BdfIndent.s
	@echo ... src/BdfList.obj
	@echo ... src/BdfList.i
	@echo ... src/BdfList.s
	@echo ... src/BdfLookupTable.obj
	@echo ... src/BdfLookupTable.i
	@echo ... src/BdfLookupTable.s
	@echo ... src/BdfNamedList.obj
	@echo ... src/BdfNamedList.i
	@echo ... src/BdfNamedList.s
	@echo ... src/BdfObject.obj
	@echo ... src/BdfObject.i
	@echo ... src/BdfObject.s
	@echo ... src/BdfReader.obj
	@echo ... src/BdfReader.i
	@echo ... src/BdfReader.s
	@echo ... src/BdfReaderHuman.obj
	@echo ... src/BdfReaderHuman.i
	@echo ... src/BdfReaderHuman.s
	@echo ... src/BdfStringReader.obj
	@echo ... src/BdfStringReader.i
	@echo ... src/BdfStringReader.s
	@echo ... src/version.obj
	@echo ... src/version.i
	@echo ... src/version.s
	@echo ... tools/bdfconvert.obj
	@echo ... tools/bdfconvert.i
	@echo ... tools/bdfconvert.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

